#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
    # Write your code here
    
    #define a temporary value
    score_a = 0
    score_b = 0
    
    #If a[i] > b[i], then Alice is awarded 1 point.
    #If a[i] < b[i], then Bob is awarded 1 point.
    #If a[i] = b[i], then neither person receives a point.
    
    for i in range(len(a)):
        if a[i] > b[i]:
            score_a += 1 #update the temporary value
        elif a[i] < b[i]:
            score_b += 1 #update the temporary value
        elif a[i] == b[i]:
            pass #no update anything
        
        score = (score_a, score_b) #define the comparative value

    return score
     
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
